# Goal: Concatenate all csv files generated by NCPac in a directory
# Author: Jonathan Yik Chang Ting
# Date: 26/7/2021
import pandas as pd
import glob


dirPath = "/g/data/q27/jt5911/SimAnneal/L10min"
allFiles = glob.glob("{0}/od_FEATURESET*csv".format(dirPath))
dfList = []
for fileName in allFiles:
    df = pd.read_csv(fileName, header=1)
    dfList.append(df)
frame = pd.concat(dfList, axis=0, ignore_index=True)
